import saleImg from '../../components/RepeaterBlocks/DiscountCardsSwiper/images/sale-1.jpeg'

import { CRUISE_ROUTES } from '../../constants'
import { ICard } from '../../model/interfaces'

export const dataSale: ICard[] = [
	{
		id: 1,
		src: saleImg,
		alt: 'Coconut cocktail on the beach',
		title: 'КРУИЗ ДНЯ',
		subtitle: 'лучшее предложение',
		href: `${CRUISE_ROUTES.EMPTY}`,
		isDiscount: false,
		discountPercentage: 0,
	},
	{
		id: 2,
		src: saleImg,
		alt: 'Coconut cocktail on the beach',
		title: 'ПЛЯЖИ',
		subtitle: 'на выходные',
		href: `${CRUISE_ROUTES.EMPTY}`,
		isDiscount: false,
		discountPercentage: 0,
	},
	{
		id: 3,
		src: saleImg,
		alt: 'Coconut cocktail on the beach',
		title: 'КАНИКУЛЫ',
		subtitle: 'на островах',
		href: `${CRUISE_ROUTES.EMPTY}`,
		isDiscount: true,
		discountPercentage: 20,
	},
	{
		id: 4,
		src: saleImg,
		alt: 'Coconut cocktail on the beach',
		title: 'ШОПИНГТУР',
		subtitle: 'на уикенд',
		href: `${CRUISE_ROUTES.EMPTY}`,
		isDiscount: true,
		discountPercentage: 25,
	},
	{
		id: 5,
		src: saleImg,
		alt: 'Coconut cocktail on the beach',
		title: 'КРУИЗ ДНЯ',
		subtitle: 'лучшее предложение',
		href: `${CRUISE_ROUTES.EMPTY}`,
		isDiscount: false,
		discountPercentage: 0,
	},
	{
		id: 6,
		src: saleImg,
		alt: 'Coconut cocktail on the beach',
		title: 'ПЛЯЖИ',
		subtitle: 'на выходные',
		href: `${CRUISE_ROUTES.EMPTY}`,
		isDiscount: false,
		discountPercentage: 0,
	},
	{
		id: 7,
		src: saleImg,
		alt: 'Coconut cocktail on the beach',
		title: 'КАНИКУЛЫ',
		subtitle: 'на островах',
		href: `${CRUISE_ROUTES.EMPTY}`,
	},
	{
		id: 8,
		src: saleImg,
		alt: 'Coconut cocktail on the beach',
		title: 'ШОПИНГТУР',
		subtitle: 'на уикенд',
		href: `${CRUISE_ROUTES.EMPTY}`,
		isDiscount: true,
		discountPercentage: 25,
	},
	{
		id: 9,
		src: saleImg,
		alt: 'Coconut cocktail on the beach',
		title: 'КРУИЗ ДНЯ',
		subtitle: 'лучшее предложение',
		href: `${CRUISE_ROUTES.EMPTY}`,
		isDiscount: true,
		discountPercentage: 20,
	},
	{
		id: 10,
		src: saleImg,
		alt: 'Coconut cocktail on the beach',
		title: 'ПЛЯЖИ',
		subtitle: 'на выходные',
		href: `${CRUISE_ROUTES.EMPTY}`,
		isDiscount: false,
		discountPercentage: 0,
	},
	{
		id: 11,
		src: saleImg,
		alt: 'Coconut cocktail on the beach',
		title: 'КАНИКУЛЫ',
		subtitle: 'на островах',
		href: `${CRUISE_ROUTES.EMPTY}`,
	},
	{
		id: 12,
		src: saleImg,
		alt: 'Coconut cocktail on the beach',
		title: 'ШОПИНГТУР',
		subtitle: 'на уикенд',
		href: `${CRUISE_ROUTES.EMPTY}`,
		isDiscount: true,
		discountPercentage: 25,
	},
	{
		id: 13,
		src: saleImg,
		alt: 'Coconut cocktail on the beach',
		title: 'КРУИЗ ДНЯ',
		subtitle: 'лучшее предложение',
		href: `${CRUISE_ROUTES.EMPTY}`,
		isDiscount: false,
		discountPercentage: 0,
	},
	{
		id: 14,
		src: saleImg,
		alt: 'Coconut cocktail on the beach',
		title: 'ПЛЯЖИ',
		subtitle: 'на выходные',
		href: `${CRUISE_ROUTES.EMPTY}`,
		isDiscount: true,
		discountPercentage: 50,
	},
	{
		id: 15,
		src: saleImg,
		alt: 'Coconut cocktail on the beach',
		title: 'КАНИКУЛЫ',
		subtitle: 'на островах',
		href: `${CRUISE_ROUTES.EMPTY}`,
	},
	{
		id: 16,
		src: saleImg,
		alt: 'Coconut cocktail on the beach',
		title: 'ШОПИНГТУР',
		subtitle: 'на уикенд',
		href: `${CRUISE_ROUTES.EMPTY}`,
	},
]
