/* eslint-disable max-len */
import { ICard } from '@crdr/interfaces'

import imgSrc1 from '@crdr/image/ship/new-ship.jpg'

export const dataFleet: ICard[] = [
	{
		title: 'MSC World Europa',
		subtitle: 'Премиальная круизная компания, собственником которой является материнская компания Royal Caribbean Cruises Ltd. Компания основана в 1989 году греческой компанией Chandris, но уже в 1997 году Celebrity Cruises Ltd объединилась с Royal Caribbean International в круизный холдинг Royal Caribbean Cruises Ltd.',
		image: { src: imgSrc1, alt: '' },
		tags: 'Средиземное море, ОАЭ',
		href: '#',
		secondaryHref: '#',
		created: '2023',
		update: '-',
	},
	{
		title: 'MSC Belissima',
		subtitle: 'Премиальная круизная компания, собственником которой является материнская компания Royal Caribbean Cruises Ltd. Компания основана в 1989 году греческой компанией Chandris, но уже в 1997 году Celebrity Cruises Ltd объединилась с Royal Caribbean International в круизный холдинг Royal Caribbean Cruises Ltd.',
		image: { src: imgSrc1, alt: '' },
		tags: 'Средиземное море',
		href: '#',
		secondaryHref: '#',
		created: '2019',
		update: '-',
	},
	{
		title: 'MSC Orchestra',
		subtitle: 'Премиальная круизная компания, собственником которой является материнская компания Royal Caribbean Cruises Ltd. Компания основана в 1989 году греческой компанией Chandris, но уже в 1997 году Celebrity Cruises Ltd объединилась с Royal Caribbean International в круизный холдинг Royal Caribbean Cruises Ltd.',
		image: { src: imgSrc1, alt: '' },
		tags: 'Средиземное море',
		href: '#',
		secondaryHref: '#',
		created: '2007',
		update: '2021',
	},
	{
		title: 'MSC World Europa',
		subtitle: 'Премиальная круизная компания, собственником которой является материнская компания Royal Caribbean Cruises Ltd. Компания основана в 1989 году греческой компанией Chandris, но уже в 1997 году Celebrity Cruises Ltd объединилась с Royal Caribbean International в круизный холдинг Royal Caribbean Cruises Ltd.',
		image: { src: imgSrc1, alt: '' },
		tags: 'Средиземное море, ОАЭ',
		href: '#',
		secondaryHref: '#',
		created: '2023',
		update: '-',
	},
	{
		title: 'MSC Belissima',
		subtitle: 'Премиальная круизная компания, собственником которой является материнская компания Royal Caribbean Cruises Ltd. Компания основана в 1989 году греческой компанией Chandris, но уже в 1997 году Celebrity Cruises Ltd объединилась с Royal Caribbean International в круизный холдинг Royal Caribbean Cruises Ltd.',
		image: { src: imgSrc1, alt: '' },
		tags: 'Средиземное море',
		href: '#',
		secondaryHref: '#',
		created: '2019',
		update: '-',
	},
	{
		title: 'MSC Orchestra',
		subtitle: 'Премиальная круизная компания, собственником которой является материнская компания Royal Caribbean Cruises Ltd. Компания основана в 1989 году греческой компанией Chandris, но уже в 1997 году Celebrity Cruises Ltd объединилась с Royal Caribbean International в круизный холдинг Royal Caribbean Cruises Ltd.',
		image: { src: imgSrc1, alt: '' },
		tags: 'Средиземное море',
		href: '#',
		secondaryHref: '#',
		created: '2007',
		update: '2021',
	},
	{
		title: 'MSC World Europa',
		subtitle: 'Премиальная круизная компания, собственником которой является материнская компания Royal Caribbean Cruises Ltd. Компания основана в 1989 году греческой компанией Chandris, но уже в 1997 году Celebrity Cruises Ltd объединилась с Royal Caribbean International в круизный холдинг Royal Caribbean Cruises Ltd.',
		image: { src: imgSrc1, alt: '' },
		tags: 'Средиземное море, ОАЭ',
		href: '#',
		secondaryHref: '#',
		created: '2023',
		update: '-',
	},
	{
		title: 'MSC Belissima',
		subtitle: 'Премиальная круизная компания, собственником которой является материнская компания Royal Caribbean Cruises Ltd. Компания основана в 1989 году греческой компанией Chandris, но уже в 1997 году Celebrity Cruises Ltd объединилась с Royal Caribbean International в круизный холдинг Royal Caribbean Cruises Ltd.',
		image: { src: imgSrc1, alt: '' },
		tags: 'Средиземное море',
		href: '#',
		secondaryHref: '#',
		created: '2019',
		update: '-',
	},
	{
		title: 'MSC Orchestra',
		subtitle: 'Премиальная круизная компания, собственником которой является материнская компания Royal Caribbean Cruises Ltd. Компания основана в 1989 году греческой компанией Chandris, но уже в 1997 году Celebrity Cruises Ltd объединилась с Royal Caribbean International в круизный холдинг Royal Caribbean Cruises Ltd.',
		image: { src: imgSrc1, alt: '' },
		tags: 'Средиземное море',
		href: '#',
		secondaryHref: '#',
		created: '2007',
		update: '2021',
	},
	{
		title: 'MSC World Europa',
		subtitle: 'Премиальная круизная компания, собственником которой является материнская компания Royal Caribbean Cruises Ltd. Компания основана в 1989 году греческой компанией Chandris, но уже в 1997 году Celebrity Cruises Ltd объединилась с Royal Caribbean International в круизный холдинг Royal Caribbean Cruises Ltd.',
		image: { src: imgSrc1, alt: '' },
		tags: 'Средиземное море, ОАЭ',
		href: '#',
		secondaryHref: '#',
		created: '2023',
		update: '-',
	},
	{
		title: 'MSC Belissima',
		subtitle: 'Премиальная круизная компания, собственником которой является материнская компания Royal Caribbean Cruises Ltd. Компания основана в 1989 году греческой компанией Chandris, но уже в 1997 году Celebrity Cruises Ltd объединилась с Royal Caribbean International в круизный холдинг Royal Caribbean Cruises Ltd.',
		image: { src: imgSrc1, alt: '' },
		tags: 'Средиземное море',
		href: '#',
		secondaryHref: '#',
		created: '2019',
		update: '-',
	},
	{
		title: 'MSC Orchestra',
		subtitle: 'Премиальная круизная компания, собственником которой является материнская компания Royal Caribbean Cruises Ltd. Компания основана в 1989 году греческой компанией Chandris, но уже в 1997 году Celebrity Cruises Ltd объединилась с Royal Caribbean International в круизный холдинг Royal Caribbean Cruises Ltd.',
		image: { src: imgSrc1, alt: '' },
		tags: 'Средиземное море',
		href: '#',
		secondaryHref: '#',
		created: '2007',
		update: '2021',
	},
]
