/* eslint-disable max-len */
import { ICard } from '@crdr/interfaces'

import logoSrc from '@crdr/image/partners/partner-celebrity.png'
import shipSrc from '@crdr/image/ship/new-ship.jpg'

export const dataAboutCompany: ICard[] = [
	{
		title: 'Сelebrity Cruises',
		subtitle: 'Премиальная круизная компания, собственником которой является материнская компания Royal Caribbean Cruises Ltd. Компания основана в 1989 году греческой компанией Chandris, но уже в 1997 году Celebrity Cruises Ltd объединилась с Royal Caribbean International в круизный холдинг Royal Caribbean Cruises Ltd. ',
		image: { src: shipSrc, alt: '' },
		tags: 'Семейных отдых, Круизы для новчков, Романтические круизы',
		href: '/company',
		secondaryHref: '#',
		fleet: '6',
		logo: logoSrc,
	},
	{
		title: 'Сelebrity Cruises',
		subtitle: 'Премиальная круизная компания, собственником которой является материнская компания Royal Caribbean Cruises Ltd. Компания основана в 1989 году греческой компанией Chandris, но уже в 1997 году Celebrity Cruises Ltd объединилась с Royal Caribbean International в круизный холдинг Royal Caribbean Cruises Ltd.',
		image: { src: shipSrc, alt: '' },
		tags: 'Семейных отдых, Круизы для новчков, Романтические круизы',
		href: '/company',
		secondaryHref: '#',
		fleet: '6',
		logo: logoSrc,
	},
	{
		title: 'Сelebrity Cruises',
		subtitle: 'Премиальная круизная компания, собственником которой является материнская компания Royal Caribbean Cruises Ltd. Компания основана в 1989 году греческой компанией Chandris, но уже в 1997 году Celebrity Cruises Ltd объединилась с Royal Caribbean International в круизный холдинг Royal Caribbean Cruises Ltd.',
		image: { src: shipSrc, alt: '' },
		tags: 'Семейных отдых, Круизы для новчков, Романтические круизы',
		href: '/company',
		secondaryHref: '#',
		fleet: '6',
		logo: logoSrc,
	},
	{
		title: 'Сelebrity Cruises',
		subtitle: 'Премиальная круизная компания, собственником которой является материнская компания Royal Caribbean Cruises Ltd. Компания основана в 1989 году греческой компанией Chandris, но уже в 1997 году Celebrity Cruises Ltd объединилась с Royal Caribbean International в круизный холдинг Royal Caribbean Cruises Ltd.',
		image: { src: shipSrc, alt: '' },
		tags: 'Семейных отдых, Круизы для новчков, Романтические круизы',
		href: '/company',
		secondaryHref: '#',
		fleet: '6',
		logo: logoSrc,
	},
	{
		title: 'Сelebrity Cruises',
		subtitle: 'Премиальная круизная компания, собственником которой является материнская компания Royal Caribbean Cruises Ltd. Компания основана в 1989 году греческой компанией Chandris, но уже в 1997 году Celebrity Cruises Ltd объединилась с Royal Caribbean International в круизный холдинг Royal Caribbean Cruises Ltd.',
		image: { src: shipSrc, alt: '' },
		tags: 'Семейных отдых, Круизы для новчков, Романтические круизы',
		href: '/company',
		secondaryHref: '#',
		fleet: '6',
		logo: logoSrc,
	},
	{
		title: 'Сelebrity Cruises',
		subtitle: 'Премиальная круизная компания, собственником которой является материнская компания Royal Caribbean Cruises Ltd. Компания основана в 1989 году греческой компанией Chandris, но уже в 1997 году Celebrity Cruises Ltd объединилась с Royal Caribbean International в круизный холдинг Royal Caribbean Cruises Ltd.',
		image: { src: shipSrc, alt: '' },
		tags: 'Семейных отдых, Круизы для новчков, Романтические круизы',
		href: '/company',
		secondaryHref: '#',
		fleet: '6',
		logo: logoSrc,
	},
	{
		title: 'Сelebrity Cruises',
		subtitle: 'Премиальная круизная компания, собственником которой является материнская компания Royal Caribbean Cruises Ltd. Компания основана в 1989 году греческой компанией Chandris, но уже в 1997 году Celebrity Cruises Ltd объединилась с Royal Caribbean International в круизный холдинг Royal Caribbean Cruises Ltd.',
		image: { src: shipSrc, alt: '' },
		tags: 'Семейных отдых, Круизы для новчков, Романтические круизы',
		href: '/company',
		secondaryHref: '#',
		fleet: '6',
		logo: logoSrc,
	},
	{
		title: 'Сelebrity Cruises',
		subtitle: 'Премиальная круизная компания, собственником которой является материнская компания Royal Caribbean Cruises Ltd. Компания основана в 1989 году греческой компанией Chandris, но уже в 1997 году Celebrity Cruises Ltd объединилась с Royal Caribbean International в круизный холдинг Royal Caribbean Cruises Ltd.',
		image: { src: shipSrc, alt: '' },
		tags: 'Семейных отдых, Круизы для новчков, Романтические круизы',
		href: '/company',
		secondaryHref: '#',
		fleet: '6',
		logo: logoSrc,
	},
	{
		title: 'Сelebrity Cruises',
		subtitle: 'Премиальная круизная компания, собственником которой является материнская компания Royal Caribbean Cruises Ltd. Компания основана в 1989 году греческой компанией Chandris, но уже в 1997 году Celebrity Cruises Ltd объединилась с Royal Caribbean International в круизный холдинг Royal Caribbean Cruises Ltd.',
		image: { src: shipSrc, alt: '' },
		tags: 'Семейных отдых, Круизы для новчков, Романтические круизы',
		href: '/company',
		secondaryHref: '#',
		fleet: '6',
		logo: logoSrc,
	},
]
