export const CRUISE_MAP = {
	aroundTheWorld: '#',
	northAmerica: '#',
	europe: '#',
	asiaFarEast: '#',
	mediterranean: '#',
	centerAmericaAndPanamaCanal: '#',
	africaAndMidEast: '#',
	pacificIslandsAndHawaii: '#',
	southAmericaAndGalapagos: '#',
	atlanticIslands: '#',
	indianOcean: '#',
	australiaAndNewZealand: '#',
	popularRegions: '#',
}
