/* eslint-disable max-len */
import { CRUISE_ROUTES } from '../../constants'
import { ICard } from '../../model/interfaces'

import shipSrc from '../../assets/images/ship/new-ship.jpg'

export const dataAboutCompany: ICard[] = [
	{
		id: 1,
		src: shipSrc,
		alt: 'Moscow city',
		title: 'Сelebrity Cruises',
		subtitle: 'Премиальная круизная компания, собственником которой является материнская компания Royal Caribbean Cruises Ltd. Компания основана в 1989 году греческой компанией Chandris, но уже в 1997 году Celebrity Cruises Ltd объединилась с Royal Caribbean International в круизный холдинг Royal Caribbean Cruises Ltd. ',
		tags: 'Семейных отдых, Круизы для новчков, Романтические круизы',
		learnMoreHref: `${CRUISE_ROUTES.EMPTY}`,
		href: '/company',
	},
	{
		id: 2,
		src: shipSrc,
		alt: 'Moscow city',
		title: 'Сelebrity Cruises',
		subtitle: 'Премиальная круизная компания, собственником которой является материнская компания Royal Caribbean Cruises Ltd. Компания основана в 1989 году греческой компанией Chandris, но уже в 1997 году Celebrity Cruises Ltd объединилась с Royal Caribbean International в круизный холдинг Royal Caribbean Cruises Ltd.',
		tags: 'Семейных отдых, Круизы для новчков, Романтические круизы',
		learnMoreHref: `${CRUISE_ROUTES.EMPTY}`,
		href: '/company',
	},
	{
		id: 3,
		src: shipSrc,
		alt: 'Moscow city',
		title: 'Сelebrity Cruises',
		subtitle: 'Премиальная круизная компания, собственником которой является материнская компания Royal Caribbean Cruises Ltd. Компания основана в 1989 году греческой компанией Chandris, но уже в 1997 году Celebrity Cruises Ltd объединилась с Royal Caribbean International в круизный холдинг Royal Caribbean Cruises Ltd.',
		tags: 'Семейных отдых, Круизы для новчков, Романтические круизы',
		learnMoreHref: `${CRUISE_ROUTES.EMPTY}`,
		href: '/company',
	},
	{
		id: 4,
		src: shipSrc,
		alt: 'Moscow city',
		title: 'Сelebrity Cruises',
		subtitle: 'Премиальная круизная компания, собственником которой является материнская компания Royal Caribbean Cruises Ltd. Компания основана в 1989 году греческой компанией Chandris, но уже в 1997 году Celebrity Cruises Ltd объединилась с Royal Caribbean International в круизный холдинг Royal Caribbean Cruises Ltd.',
		tags: 'Семейных отдых, Круизы для новчков, Романтические круизы',
		learnMoreHref: `${CRUISE_ROUTES.EMPTY}`,
		href: '/company',
	},
	{
		id: 5,
		src: shipSrc,
		alt: 'Moscow city',
		title: 'Сelebrity Cruises',
		subtitle: 'Премиальная круизная компания, собственником которой является материнская компания Royal Caribbean Cruises Ltd. Компания основана в 1989 году греческой компанией Chandris, но уже в 1997 году Celebrity Cruises Ltd объединилась с Royal Caribbean International в круизный холдинг Royal Caribbean Cruises Ltd.',
		tags: 'Семейных отдых, Круизы для новчков, Романтические круизы',
		learnMoreHref: `${CRUISE_ROUTES.EMPTY}`,
		href: '/company',
	},
	{
		id: 6,
		src: shipSrc,
		alt: 'Moscow city',
		title: 'Сelebrity Cruises',
		subtitle: 'Премиальная круизная компания, собственником которой является материнская компания Royal Caribbean Cruises Ltd. Компания основана в 1989 году греческой компанией Chandris, но уже в 1997 году Celebrity Cruises Ltd объединилась с Royal Caribbean International в круизный холдинг Royal Caribbean Cruises Ltd.',
		tags: 'Семейных отдых, Круизы для новчков, Романтические круизы',
		learnMoreHref: `${CRUISE_ROUTES.EMPTY}`,
		href: '/company',
	},
	{
		id: 7,
		src: shipSrc,
		alt: 'Moscow city',
		title: 'Сelebrity Cruises',
		subtitle: 'Премиальная круизная компания, собственником которой является материнская компания Royal Caribbean Cruises Ltd. Компания основана в 1989 году греческой компанией Chandris, но уже в 1997 году Celebrity Cruises Ltd объединилась с Royal Caribbean International в круизный холдинг Royal Caribbean Cruises Ltd.',
		tags: 'Семейных отдых, Круизы для новчков, Романтические круизы',
		learnMoreHref: `${CRUISE_ROUTES.EMPTY}`,
		href: '/company',
	},
	{
		id: 8,
		src: shipSrc,
		alt: 'Moscow city',
		title: 'Сelebrity Cruises',
		subtitle: 'Премиальная круизная компания, собственником которой является материнская компания Royal Caribbean Cruises Ltd. Компания основана в 1989 году греческой компанией Chandris, но уже в 1997 году Celebrity Cruises Ltd объединилась с Royal Caribbean International в круизный холдинг Royal Caribbean Cruises Ltd.',
		tags: 'Семейных отдых, Круизы для новчков, Романтические круизы',
		learnMoreHref: `${CRUISE_ROUTES.EMPTY}`,
		href: '/company',
	},
	{
		id: 9,
		src: shipSrc,
		alt: 'Moscow city',
		title: 'Сelebrity Cruises',
		subtitle: 'Премиальная круизная компания, собственником которой является материнская компания Royal Caribbean Cruises Ltd. Компания основана в 1989 году греческой компанией Chandris, но уже в 1997 году Celebrity Cruises Ltd объединилась с Royal Caribbean International в круизный холдинг Royal Caribbean Cruises Ltd.',
		tags: 'Семейных отдых, Круизы для новчков, Романтические круизы',
		learnMoreHref: `${CRUISE_ROUTES.EMPTY}`,
		href: '/company',
	},
]
